title: 'Unsupervised feature extraction and clustering of aerial images for understanding hazardous road segments '
description: 'Website supporting the project Unsupervised feature extraction and clustering of aerial images for understanding hazardous road segments ' 
toc: true
author: Public Policy Programme, Alan Turing Institute
baseurl: /ai-gov-framework
show_excerpts: true 

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
