title: 'Artificial intelligence in government: Concepts, standards, and a unified framework'
description: 'Website supporting the project Artificial intelligence in government: Concepts, standards, and a unified framework' 
toc: true
author: Public Policy Programme, Alan Turing Institute
baseurl: /ai-gov-framework
show_excerpts: true 

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
